/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei/native';
import {STRAWBERRY, GEAR} from '../3dfiles';
import {useLoader} from '@react-three/fiber/native';
import {OBJLoader} from 'three/examples/jsm/loaders/OBJLoader';

export function Model() {
  const obj = useLoader(OBJLoader, GEAR);
  return <primitive object={obj} scale={10.0} />;
}

/*export function Model(props) {
  const { nodes, materials } = useGLTF(STRAWBERRY);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.strawberry.geometry}
        material={materials.Strawberry}
        rotation={[-0.05, -1.23, 1.54]}
        scale={1.22}
      />
    </group>
  );
}

useGLTF.preload(STRAWBERRY);*/

/*console.log('creating storage object');

const {Storage} = require('@google-cloud/storage');
const storage = new Storage({
  projectId: 'cardiopedia',
  credentials: {
    type: 'service_account',
    project_id: 'cardiopedia',
    private_key_id: '5f78b512f74f963160e82ce24a911530d16e5048',
    private_key:
      '-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3tKyncmRTpcjY\ncMoODbYImy764+WN7pdBAwVvIKP4Z2RNfeHCgx01HttgseuiDWNG9sb0JIaKGpB6\nkum5u/GzjI5uGessKcFxwxBf3OCZRwu/mE9SVzlHBnlo4aQIQecC34hgl+CC9zG2\nUiYgqXDaOi5joxbTq1v5WK0I3Q04N8WegCDVE1yI61AI1fODkT4G/1fFE2B7VueK\nILb6x3TK5Gw2DfcJ0X2WoCR2tYvXGCYisOPvdGFECU+V4l3/4kb6EG9MeK4XIyyQ\nh4CJlcxWEODDQf1bdQihZe8hSt6dUltdDNifeEPtfRFZxhxOSd4FHkkMY8w62qJ8\n9BakFl6DAgMBAAECggEAC0Q7aobrfEMopDhBTByvKKv2dPtRHXlKhs7b9crMrklj\nr2pO/uec/PWy1/qmzD4snoeNVXUqrdb0kW/n1wpIco3mQP5km/Abpbx5iUePRsHt\nXdzGJfNPgfmgVzxaG7Te/srIHxRxd9bCkmn2CKlw+xFNEwic4nJvUPA3/IPXcbZv\nN8n4q+qkMaeAOzb8LpX3qvsc5g6ZVpoAfGV2h0BvtXYmoKNLZUJiLZiDigaBadi/\n6Z+YWQ7smKGtQrzIGnBg4xBpuMVljG1xULlfP5UodkOfLwuSGPJLvs9YBdOAdK9c\nk505SpY/jnPF3VXBE1iRk0phJcaWHwU7rdun0zy+EQKBgQDuQmLWQnLEKA47eVlX\nVyN6RBALIZ8LA47++Uxo7lPwES9KtyXzJoGXf2dKA2FBVvZ7AD3uL2SCGHmKiZex\nnAzkzcs2lGVSeG643m7puDLPST5g9O6HUsL48lxQgw6AEGCS4QmAeJAC0NEOlPny\n2tqi3BZL9H0gSIJuAWymxLmw1wKBgQDFYmhrMLZp0mHoL2dq8hPF0vpY1dh/FqvQ\njLa8O6Y9vITYtYRFacJTY0TXD8v7q26J/aqWFeFmA3Xq5bEJbh74OYU+7YxaRbo+\nOeLrbNrE8+89A5wKMQJE8eMucgVy4LCm4LOr5eK5qGmqdpuaM2zhJqf/dhjz2+GQ\nzyKyOa8ONQKBgC3RcGZZsu5L8ai4RlkIddceXaN2XLpmfcpEsNAA/P1OoLSSkea3\ngfZbVsah7cL98TpoKoCydnaaNE1S9mv+YXBirvCZCv8YD9rXU6b4eDTqledZUsGN\nRddP7DbDbTdtbtTwF76v8KnJ9FoEhiiQs7jb8CG9K47YwtRay8UqUbdTAoGAW/WW\nGmJuiezHSopTT0MLLT42/o5auBMS5y23sQjFUbvz1Jb00fYM4Ba+qsekTFM5Q7bX\n8+arxYBVPqPWkEMq0JDT4FaB7kjQFU+YxgBICDxxuGZnG2Rr3z0mj6v1l+jQxF6p\ntqt6ru6klBOAOR4+WsNMv7sAsxQ9Cd9HFevEAAUCgYEAiVFSvSy2I1tCT8YzINyH\nin8KG3yAXWx/iIu8XQ8zgbcMHHFMeEWKzAczpq7iEjMkyHfDGzLJ/VNndIhMFzx9\n/sIb1KCXOvTHFekCcq+OwpbZ1RZVlCIWGDl+1ytmC/3k/drziwM98syf+1djwgs6\nEhBZ/4nXBUNg7VHlhVFasOk=\n-----END PRIVATE KEY-----\n',
    client_email: 'cardio-admin@cardiopedia.iam.gserviceaccount.com',
    client_id: '107546216747077441877',
    auth_uri: 'https://accounts.google.com/o/oauth2/auth',
    token_uri: 'https://oauth2.googleapis.com/token',
    auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs',
    client_x509_cert_url:
      'https://www.googleapis.com/robot/v1/metadata/x509/cardio-admin%40cardiopedia.iam.gserviceaccount.com',
  },
});

console.log('created storage object');

export function Model() {
  const bucketName = 'cardiopedia-3d';
  const fileName = '16_TAPVRtoCS_Labeled.gltf';

  const bucket = storage.bucket(bucketName);
  const file = bucket.file(fileName);
  let modelBytes = null;
  file.download().then(data => {
    modelBytes = data[0];
  });

  const gltf = useLoader(GLTFLoader, modelBytes);

  return <primitive object={gltf.scene} />;
}*/
